=== matthewpang/xsd-4.0.0-aarch64-linux-gnu/xsd-4.0.0-aarch64-linux-gnu/tests/cxx/tree/encoding/char/utf-8/test.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:t="test" targetNamespace="test">

  <simpleType name="strenum">

    <annotation>
      <documentation>
        Test enum. Valid values are:
        abc
        a&#x555;c
        &#xAAAA;bc
        ab&#xAAAAA;
      </documentation>
    </annotation>

    <restriction base="string">
      <enumeration value="abc"/>
      <enumeration value="a&#x555;c"/>
      <enumeration value="&#xAAAA;bc"/>
      <enumeration value="ab&#xAAAAA;"/>
    </restriction>
  </simpleType>

  <complexType name="type">
    <sequence>
      <element name="a" type="string" maxOccurs="unbounded"/>
      <element name="b" type="t:strenum" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="root" type="t:type"/>

</schema>

=== matthewpang/xsd-4.0.0-aarch64-linux-gnu/xsd-4.0.0-aarch64-linux-gnu/tests/cxx/tree/encoding/char/utf-8/test.xml
<t:root xmlns:t="test"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd">

  <a>abc</a>
  <a>&#x555;</a>
  <a>&#xAAAA;</a>
  <a>&#xAAAAA;</a>

  <b>abc</b>
  <b>a&#x555;c</b>
  <b>&#xAAAA;bc</b>
  <b>ab&#xAAAAA;</b>

</t:root>
