=== matthewpang/xsd-4.0.0-aarch64-linux-gnu/xsd-4.0.0+dep/xsd/tests/cxx/tree/comparison/test.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:t="test" targetNamespace="test">

  <complexType name="member">
    <simpleContent>
      <extension base="string">
        <attribute name="x" type="int" use="required"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="complex">
    <sequence>
      <element name="a" type="int"/>
      <element name="b" type="string" minOccurs="0"/>
      <element name="c" type="t:member" maxOccurs="unbounded"/>
    </sequence>
      <attribute name="x" type="int"/>
      <attribute name="y" type="string" use="required"/>
  </complexType>

  <complexType name="type">
    <sequence>
      <element name="complex" type="t:complex" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="root" type="t:type"/>

</schema>

=== matthewpang/xsd-4.0.0-aarch64-linux-gnu/xsd-4.0.0+dep/xsd/tests/cxx/tree/comparison/test.xml
<t:root xmlns:t="test"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd">

  <complex x="123" y="abc">
    <a>123</a>
    <b>abc</b>
    <c x="123">abc</c>
    <c x="456">def</c>
  </complex>

  <complex x="123" y="abc">
    <a>123</a>
    <b>abc</b>
    <c x="123">abc</c>
    <c x="456">xyz</c>
  </complex>

</t:root>
