=== matthewpang/xsd-4.0.0-aarch64-linux-gnu/xsd-4.0.0+dep/xsd/tests/cxx/tree/float/test.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:t="test" targetNamespace="test">

  <simpleType name="float-list">
    <list itemType="float"/>
  </simpleType>

  <simpleType name="double-list">
    <list itemType="double"/>
  </simpleType>

  <simpleType name="decimal-list">
    <list itemType="decimal"/>
  </simpleType>

  <!-- decimal facets -->

  <simpleType name="simple">
    <restriction base="t:base-simple">
      <fractionDigits value="2"/>
    </restriction>
  </simpleType>

  <simpleType name="base-simple">
    <restriction base="decimal">
      <totalDigits value="4"/>
    </restriction>
  </simpleType>

  <complexType name="complex">
    <simpleContent>
      <restriction base="t:base-complex">
       <fractionDigits value="2"/>
       <totalDigits value="4"/>
       <attribute name="x" type="int"/>
      </restriction>
    </simpleContent>
  </complexType>

  <complexType name="base-complex">
    <simpleContent>
      <extension base="decimal">
       <attribute name="x" type="int"/>
      </extension>
    </simpleContent>
  </complexType>


  <complexType name="type">
    <sequence>
      <element name="float" type="float" maxOccurs="unbounded"/>
      <element name="float-list" type="t:float-list"/>
      <element name="double" type="double" maxOccurs="unbounded"/>
      <element name="double-list" type="t:double-list"/>
      <element name="decimal" type="decimal" maxOccurs="unbounded"/>
      <element name="decimal-list" type="t:decimal-list"/>

      <element name="simple" type="t:simple" maxOccurs="unbounded"/>
      <element name="complex" type="t:complex" maxOccurs="unbounded"/>

    </sequence>
    <attribute name="f" type="float" default="12.34"/>
    <attribute name="do" type="double" default="1234.1234"/>
    <attribute name="de" type="decimal" default="1234.1234"/>

    <attribute name="s" type="t:simple"/>
  </complexType>

  <element name="root" type="t:type"/>

  <element name="double" type="double"/>
  <element name="decimal" type="decimal"/>

</schema>

=== matthewpang/xsd-4.0.0-aarch64-linux-gnu/xsd-4.0.0+dep/xsd/tests/cxx/tree/float/test.xml
<t:root xmlns:t="test"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd"
        f="0.0" do="0.0" de="0.0">

  <float>0.0</float>
  <float>1.0</float>
  <float>1000000.0</float>
  <float>0.0000001</float>
  <float-list>0.0 1.0 1000000.0 0.0000001</float-list>

  <double>0.0</double>
  <double>1.0</double>
  <double>100000000000000.0</double>
  <double>0.000000000000001</double>
  <double-list>0.0 1.0 100000000000000.0 0.000000000000001</double-list>

  <decimal>0.0</decimal>
  <decimal>1.0</decimal>
  <decimal>10000</decimal>
  <decimal>100000000000000.0</decimal>
  <decimal>0.000000000000001</decimal>
  <decimal-list>0.0 1.0 100000000000000.0 0.000000000000001</decimal-list>

  <simple>0.0</simple>
  <simple>1.0</simple>
  <simple>12.34</simple>
  <simple>0.12</simple>

  <complex>0.0</complex>
  <complex>1.0</complex>
  <complex>12.34</complex>
  <complex>0.12</complex>

</t:root>
