=== matthewpang/xsd-4.0.0-aarch64-linux-gnu/xsd-4.0.0+dep/xsd/tests/cxx/tree/polymorphism/ostream/test.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:t="test"
        targetNamespace="test" elementFormDefault="qualified">

  <complexType name="base">
    <sequence>
      <element name="a" type="string"/>
      <element name="fund" type="int"/>
    </sequence>
  </complexType>
  <element name="base" type="t:base"/>

  <complexType name="derived1">
    <complexContent>
      <extension base="t:base">
        <sequence>
          <element name="b" type="string" minOccurs="0"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="derived2">
    <complexContent>
      <extension base="t:base">
        <sequence>
          <element name="c" type="string" maxOccurs="unbounded"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <element name="derived3" substitutionGroup="t:base">
    <complexType>
      <complexContent>
        <extension base="t:base">
          <sequence>
            <element name="d" type="string" maxOccurs="unbounded"/>
          </sequence>
        </extension>
      </complexContent>
    </complexType>
  </element>

  <complexType name="type">
    <sequence>
      <element ref="t:base" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="root" type="t:type"/>

</schema>

=== matthewpang/xsd-4.0.0-aarch64-linux-gnu/xsd-4.0.0+dep/xsd/tests/cxx/tree/polymorphism/ostream/test.xml
<root xmlns="test"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="test test.xsd">

  <base><a>a</a><fund>1</fund></base>
  <base xsi:type="derived1"><a>a</a><fund>1</fund><b>b</b></base>
  <base xsi:type="derived2"><a>a</a><fund>1</fund><c>c1</c><c>c2</c></base>
  <derived3><a>a</a><fund>1</fund><d>d1</d><d>d2</d></derived3>

</root>
