=== matthewpang/xsd-4.0.0-aarch64-linux-gnu/xsd-4.0.0-aarch64-linux-gnu/tests/cxx/tree/polymorphism/same-type/test.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:t="test" targetNamespace="test">

  <complexType name="base">
    <sequence>
      <element name="a" type="string"/>
    </sequence>
  </complexType>

  <element name="base" type="t:base"/>
  <element name="derived" type="t:base" substitutionGroup="t:base"/>

  <complexType name="type">
    <sequence>
      <element ref="t:base" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="root" type="t:type"/>

</schema>

=== matthewpang/xsd-4.0.0-aarch64-linux-gnu/xsd-4.0.0+dep/xsd/tests/cxx/tree/polymorphism/same-type/test.xml
<t:root xmlns:t="test"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd">

  <t:base><a>a1</a></t:base>
  <t:derived><a>a2</a></t:derived>
  <t:base xsi:type="t:base"><a>a3</a></t:base>
  <t:derived xsi:type="t:base"><a>a4</a></t:derived>

</t:root>
